use crate::assets;
use telorgon::app::*;

pub fn cursor_theme() -> CursorTheme {
    CursorTheme::new()
        .size(32.0)
        .default_pointer(cursor(assets::cursors::ARROW).hotspot(6, 4))
        .pointer(cursor(assets::cursors::POINTER).hotspot(14, 5))
        .text(cursor(assets::cursors::TEXT).hotspot(16, 16))
        .vertical_text(cursor(assets::cursors::VERTICAL_TEXT).hotspot(16, 16))
        .crosshair(cursor(assets::cursors::CROSSHAIR).hotspot(16, 16))
        .cell(cursor(assets::cursors::CROSSHAIR).hotspot(16, 16))
        .move_cursor(cursor(assets::cursors::MOVE).hotspot(16, 16))
        .all_resize(cursor(assets::cursors::MOVE).hotspot(16, 16))
        .all_scroll(cursor(assets::cursors::MOVE).hotspot(16, 16))
        .grab(cursor(assets::cursors::GRAB).hotspot(16, 16))
        .grabbing(cursor(assets::cursors::GRABBING).hotspot(16, 16))
        .not_allowed(cursor(assets::cursors::NOT_ALLOWED).hotspot(16, 16))
        .no_drop(cursor(assets::cursors::NOT_ALLOWED).hotspot(16, 16))
        .wait(cursor(assets::cursors::WAIT).hotspot(16, 16))
        .progress(cursor(assets::cursors::PROGRESS).hotspot(6, 4))
        .copy(cursor(assets::cursors::COPY).hotspot(5, 3))
        .alias(cursor(assets::cursors::ALIAS).hotspot(5, 3))
        .help(cursor(assets::cursors::HELP).hotspot(5, 3))
        .dnd_ask(cursor(assets::cursors::HELP).hotspot(5, 3))
        .context_menu(cursor(assets::cursors::ARROW).hotspot(6, 4))
        .zoom_in(cursor(assets::cursors::ZOOM_IN).hotspot(16, 13))
        .zoom_out(cursor(assets::cursors::ZOOM_OUT).hotspot(16, 13))
        .e_resize(cursor(assets::cursors::RESIZE_EW).hotspot(16, 16))
        .w_resize(cursor(assets::cursors::RESIZE_EW).hotspot(16, 16))
        .ew_resize(cursor(assets::cursors::RESIZE_EW).hotspot(16, 16))
        .col_resize(cursor(assets::cursors::RESIZE_EW).hotspot(16, 16))
        .n_resize(cursor(assets::cursors::RESIZE_NS).hotspot(16, 16))
        .s_resize(cursor(assets::cursors::RESIZE_NS).hotspot(16, 16))
        .ns_resize(cursor(assets::cursors::RESIZE_NS).hotspot(16, 16))
        .row_resize(cursor(assets::cursors::RESIZE_NS).hotspot(16, 16))
        .nw_resize(cursor(assets::cursors::RESIZE_NWSE).hotspot(16, 16))
        .se_resize(cursor(assets::cursors::RESIZE_NWSE).hotspot(16, 16))
        .nwse_resize(cursor(assets::cursors::RESIZE_NWSE).hotspot(16, 16))
        .ne_resize(cursor(assets::cursors::RESIZE_NESW).hotspot(16, 16))
        .sw_resize(cursor(assets::cursors::RESIZE_NESW).hotspot(16, 16))
        .nesw_resize(cursor(assets::cursors::RESIZE_NESW).hotspot(16, 16))
}
